// <auto-generated />
using InterestHub2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterestHub2.Migrations
{
    [DbContext(typeof(InterestHubDbContext))]
    [Migration("20230506144751_firstTablesCreate")]
    partial class firstTablesCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterestHub2.Models.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("InterestId");

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("InterestHub2.Models.InterestLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FK_InterestId")
                        .HasColumnType("int");

                    b.Property<int>("FK_LinkId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FK_InterestId");

                    b.HasIndex("FK_LinkId");

                    b.ToTable("InterestLinks");
                });

            modelBuilder.Entity("InterestHub2.Models.Link", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LinkId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("InterestHub2.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InterestHub2.Models.UserInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FK_InterestId")
                        .HasColumnType("int");

                    b.Property<int>("FK_UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FK_InterestId");

                    b.HasIndex("FK_UserId");

                    b.ToTable("UserInterests");
                });

            modelBuilder.Entity("InterestHub2.Models.UserInterestLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FK_InterestId")
                        .HasColumnType("int");

                    b.Property<int>("FK_LinkId")
                        .HasColumnType("int");

                    b.Property<int>("FK_UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FK_InterestId");

                    b.HasIndex("FK_LinkId");

                    b.HasIndex("FK_UserId");

                    b.ToTable("UserInterestLinks");
                });

            modelBuilder.Entity("InterestHub2.Models.InterestLink", b =>
                {
                    b.HasOne("InterestHub2.Models.Interest", "Interests")
                        .WithMany("InterestLinks")
                        .HasForeignKey("FK_InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterestHub2.Models.Link", "Links")
                        .WithMany("InterestLinks")
                        .HasForeignKey("FK_LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interests");

                    b.Navigation("Links");
                });

            modelBuilder.Entity("InterestHub2.Models.UserInterest", b =>
                {
                    b.HasOne("InterestHub2.Models.Interest", "Interests")
                        .WithMany("UserInterests")
                        .HasForeignKey("FK_InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterestHub2.Models.User", "Users")
                        .WithMany("UserInterests")
                        .HasForeignKey("FK_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interests");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("InterestHub2.Models.UserInterestLink", b =>
                {
                    b.HasOne("InterestHub2.Models.Interest", "Interests")
                        .WithMany("UserInterestLinks")
                        .HasForeignKey("FK_InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterestHub2.Models.Link", "Links")
                        .WithMany("UserInterestLinks")
                        .HasForeignKey("FK_LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterestHub2.Models.User", "Users")
                        .WithMany("UserInterestLinks")
                        .HasForeignKey("FK_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interests");

                    b.Navigation("Links");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("InterestHub2.Models.Interest", b =>
                {
                    b.Navigation("InterestLinks");

                    b.Navigation("UserInterestLinks");

                    b.Navigation("UserInterests");
                });

            modelBuilder.Entity("InterestHub2.Models.Link", b =>
                {
                    b.Navigation("InterestLinks");

                    b.Navigation("UserInterestLinks");
                });

            modelBuilder.Entity("InterestHub2.Models.User", b =>
                {
                    b.Navigation("UserInterestLinks");

                    b.Navigation("UserInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
